version: "3.3"
services: 
    proxy:
      image: nginx:latest
      container_name: proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 0.0.0.0:80:80/tcp
volumes:
  share: {}
